// Database types - will be regenerated by Supabase CLI
// Run: supabase gen types typescript --project-id sisrlbxaijnfrrvfjhli > src/shared/types/database.ts

export interface Database {
    public: {
        Tables: {
            reefs: {
                Row: {
                    id: string
                    name: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    name?: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    created_at?: string
                }
            }
            profiles: {
                Row: {
                    id: string
                    display_name: string
                    avatar_url: string | null
                    reef_id: string | null
                    role: 'husband' | 'wife' | null
                    created_at: string
                }
                Insert: {
                    id: string
                    display_name: string
                    avatar_url?: string | null
                    reef_id?: string | null
                    role?: 'husband' | 'wife' | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    display_name?: string
                    avatar_url?: string | null
                    reef_id?: string | null
                    role?: 'husband' | 'wife' | null
                    created_at?: string
                }
            }
            system_prompts: {
                Row: {
                    key: string
                    prompt_text: string
                    description: string | null
                    version: number
                    updated_at: string
                }
                Insert: {
                    key: string
                    prompt_text: string
                    description?: string | null
                    version?: number
                    updated_at?: string
                }
                Update: {
                    key?: string
                    prompt_text?: string
                    description?: string | null
                    version?: number
                    updated_at?: string
                }
            }
            bridge_messages: {
                Row: {
                    id: string
                    reef_id: string
                    sender_id: string
                    recipient_id: string
                    emotion: string
                    original_text: string
                    transformed_text: string | null
                    ai_analysis: Record<string, unknown>
                    acknowledged_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    reef_id: string
                    sender_id: string
                    recipient_id: string
                    emotion: string
                    original_text: string
                    transformed_text?: string | null
                    ai_analysis?: Record<string, unknown>
                    acknowledged_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    reef_id?: string
                    sender_id?: string
                    recipient_id?: string
                    emotion?: string
                    original_text?: string
                    transformed_text?: string | null
                    ai_analysis?: Record<string, unknown>
                    acknowledged_at?: string | null
                    created_at?: string
                }
            }
            retros: {
                Row: {
                    id: string
                    reef_id: string
                    title: string
                    event_date: string | null
                    status: 'pending' | 'submitted' | 'revealed'
                    ai_summary: Record<string, unknown>
                    created_at: string
                }
                Insert: {
                    id?: string
                    reef_id: string
                    title: string
                    event_date?: string | null
                    status?: 'pending' | 'submitted' | 'revealed'
                    ai_summary?: Record<string, unknown>
                    created_at?: string
                }
                Update: {
                    id?: string
                    reef_id?: string
                    title?: string
                    event_date?: string | null
                    status?: 'pending' | 'submitted' | 'revealed'
                    ai_summary?: Record<string, unknown>
                    created_at?: string
                }
            }
            retro_submissions: {
                Row: {
                    id: string
                    retro_id: string
                    author_id: string
                    raw_narrative: string
                    ai_analysis: Record<string, unknown>
                    future_script: string | null
                    submitted_at: string
                }
                Insert: {
                    id?: string
                    retro_id: string
                    author_id: string
                    raw_narrative: string
                    ai_analysis?: Record<string, unknown>
                    future_script?: string | null
                    submitted_at?: string
                }
                Update: {
                    id?: string
                    retro_id?: string
                    author_id?: string
                    raw_narrative?: string
                    ai_analysis?: Record<string, unknown>
                    future_script?: string | null
                    submitted_at?: string
                }
            }
        }
    }
}
